from collections.abc import AsyncGenerator

from app.core.config import settings
from app.services.embeddings import get_openai_client

SYSTEM_PROMPT = (
    "You are a helpful assistant that answers questions using ONLY the "
    "provided context excerpts. If the context does not contain enough "
    "information to answer confidently, say so explicitly instead of "
    "guessing. Cite which excerpt(s) you used when relevant, e.g. [1], [2]."
)


def _build_prompt(query: str, context_chunks: list[str]) -> list[dict]:
    context_block = "\n\n".join(
        f"[{i + 1}] {chunk}" for i, chunk in enumerate(context_chunks)
    ) or "(no relevant context found)"

    user_message = (
        f"Context excerpts:\n{context_block}\n\n"
        f"Question: {query}\n\n"
        "Answer the question using only the context above."
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ]


async def generate_answer(query: str, context_chunks: list[str]) -> str:
    """Generate a single, complete answer (non-streaming)."""
    client = get_openai_client()
    messages = _build_prompt(query, context_chunks)
    response = await client.chat.completions.create(
        model=settings.CHAT_MODEL,
        messages=messages,
        temperature=0.2,
    )
    return response.choices[0].message.content or ""


async def generate_answer_stream(query: str, context_chunks: list[str]) -> AsyncGenerator[str, None]:
    """Yield the answer incrementally as it is generated by the LLM."""
    client = get_openai_client()
    messages = _build_prompt(query, context_chunks)
    stream = await client.chat.completions.create(
        model=settings.CHAT_MODEL,
        messages=messages,
        temperature=0.2,
        stream=True,
    )
    async for event in stream:
        delta = event.choices[0].delta.content if event.choices else None
        if delta:
            yield delta
