from collections.abc import AsyncGenerator

from google.genai import types

from app.core.config import settings
from app.services.embeddings import get_genai_client

SYSTEM_PROMPT = (
    "You are a helpful assistant that answers questions using ONLY the "
    "provided context excerpts. If the context does not contain enough "
    "information to answer confidently, say so explicitly instead of "
    "guessing. Cite which excerpt(s) you used when relevant, e.g. [1], [2]."
)


def _build_user_message(query: str, context_chunks: list[str]) -> str:
    context_block = "\n\n".join(
        f"[{i + 1}] {chunk}" for i, chunk in enumerate(context_chunks)
    ) or "(no relevant context found)"

    return (
        f"Context excerpts:\n{context_block}\n\n"
        f"Question: {query}\n\n"
        "Answer the question using only the context above."
    )


async def generate_answer(query: str, context_chunks: list[str]) -> str:
    """Generate a single, complete answer (non-streaming)."""
    client = get_genai_client()
    response = await client.aio.models.generate_content(
        model=settings.CHAT_MODEL,
        contents=_build_user_message(query, context_chunks),
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=0.2,
        ),
    )
    return response.text or ""


async def generate_answer_stream(query: str, context_chunks: list[str]) -> AsyncGenerator[str, None]:
    """Yield the answer incrementally as it is generated by the LLM."""
    client = get_genai_client()
    stream = await client.aio.models.generate_content_stream(
        model=settings.CHAT_MODEL,
        contents=_build_user_message(query, context_chunks),
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=0.2,
        ),
    )
    async for chunk in stream:
        if chunk.text:
            yield chunk.text
